server.port = 8081

spring.application.name = testServer
spring.profiles.active = dev
spring.jackson.date-format = com.fasterxml.jackson.databind.util.ISO8601DateFormat
spring.jackson.time-zone = UTC
spring.thymeleaf.mode = HTML5
spring.web.resources.chain.cache = true
spring.web.resources.chain.enabled = true
spring.web.resources.cache.period = 604800

spring.boot.admin.url = http://localhost:8081
spinrg.boot.admin.client.metadata.user.name = ${security.user.name}
spinrg.boot.admin.client.metadata.user.password = ${security.user.password}

management.security.enabled : ture

security.user.name = admin
security.user.password = 123456

spring.h2.console.enabled = true

spring.datasource.url = jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username = sa
spring.datasource.password = password

spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization = true
#spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.show-sql = true
#spring.jpa.generate-ddl = false

spring.cache.cache-names = getTime, currentTimeMillis
spring.cache.caffeine.spec = maximumSize=10, expireAfterWrite=5s