server:
  port: 8081

spring:
  application:
    name: testClientService
  profiles:
    active: dev
  boot:
    admin:
      url: http://localhost:8081

  management:
    security:
      enabled: false

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    #hibernate:ddl-auto: create-drop
    show-sql: true
    #generate-ddl: false

#  cache:
#    cache-names: getTime, currentTimeMillis
#    caffeine:spec: maximumSize=100, expireAfterWrite=5s